-- MÉTHODE TEE · V338 · SUIVIS PERSONNALISÉS
-- Architecture volontairement légère : 2 tables, aucune requête au démarrage de l'app.
-- Les lectures/écritures ne se font qu'à l'ouverture explicite de « Mes repères ».

create table if not exists public.user_tracker_preferences (
  user_id uuid not null references auth.users(id) on delete cascade,
  tracker_key text not null,
  enabled boolean not null default true,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, tracker_key)
);

create table if not exists public.user_tracker_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tracker_key text not null,
  entry_date date not null default current_date,
  values jsonb not null default '{}'::jsonb,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, tracker_key, entry_date)
);

-- Index utiles pour les requêtes futures 7/30/90 jours, sans scan global.
create index if not exists idx_user_tracker_entries_user_date
  on public.user_tracker_entries (user_id, entry_date desc);

create index if not exists idx_user_tracker_entries_user_key_date
  on public.user_tracker_entries (user_id, tracker_key, entry_date desc);

alter table public.user_tracker_preferences enable row level security;
alter table public.user_tracker_entries enable row level security;

-- Preferences : chaque personne ne voit/modifie que ses propres choix.
drop policy if exists "tracker preferences select own" on public.user_tracker_preferences;
create policy "tracker preferences select own"
  on public.user_tracker_preferences for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "tracker preferences insert own" on public.user_tracker_preferences;
create policy "tracker preferences insert own"
  on public.user_tracker_preferences for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "tracker preferences update own" on public.user_tracker_preferences;
create policy "tracker preferences update own"
  on public.user_tracker_preferences for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "tracker preferences delete own" on public.user_tracker_preferences;
create policy "tracker preferences delete own"
  on public.user_tracker_preferences for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Entries : même isolation stricte.
drop policy if exists "tracker entries select own" on public.user_tracker_entries;
create policy "tracker entries select own"
  on public.user_tracker_entries for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "tracker entries insert own" on public.user_tracker_entries;
create policy "tracker entries insert own"
  on public.user_tracker_entries for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "tracker entries update own" on public.user_tracker_entries;
create policy "tracker entries update own"
  on public.user_tracker_entries for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "tracker entries delete own" on public.user_tracker_entries;
create policy "tracker entries delete own"
  on public.user_tracker_entries for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Permissions REST pour les comptes connectés.
grant select, insert, update, delete on public.user_tracker_preferences to authenticated;
grant select, insert, update, delete on public.user_tracker_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;
