-- MÉTHODE TEE V478B — « Oreille Méthode TEE » · Phase 2 (correctif PostgreSQL)
-- Dépendance : V477_FOOD_IDENTITY_MULTIMODALE_PHASE1.sql déjà appliqué.
-- V478 initiale pouvait échouer au backfill à cause d'une référence LATERAL à la table cible d'un UPDATE.
-- Cette version est idempotente et peut être exécutée directement même après cet échec.
--
-- Objectifs :
-- 1) relier la future saisie vocale au catalogue culturel + CIQUAL SANS copier CIQUAL ;
-- 2) dédupliquer les doublons historiques uniquement dans les résultats vocaux ;
-- 3) distinguer une expression exacte (« taro sauce jaune ») d'un ingrédient ambigu (« taro ») ;
-- 4) permettre des alias de transcription/phonétiques administrables ;
-- 5) garder toutes les logiques actuelles (Carnet, protocoles, XP, déblocages, recherche) intactes.
--
-- ADDITIF : aucune fonction actuelle de recherche n'est remplacée.
-- Aucun appel IA, aucune photo, aucun upload, aucune écriture dans les repas/protocoles.

begin;

-- ---------------------------------------------------------------------------
-- 0. GARDE-FOU : V477 doit être présente avant toute modification.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema='public' and table_name='food_dictionary' and column_name='multimodal_key'
  ) or not exists (
    select 1
    from information_schema.columns
    where table_schema='public' and table_name='food_dictionary' and column_name='speech_aliases'
  ) then
    raise exception 'V478 nécessite V477 : multimodal_key / speech_aliases introuvables dans public.food_dictionary';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 1. VOCABULAIRE VOCAL MANUEL / PHONÉTIQUE
-- ---------------------------------------------------------------------------
-- Les alias historiques restent dans food_dictionary.aliases / speech_aliases.
-- Cette table sert uniquement aux variantes typiques de dictée vocale et peut être
-- enrichie plus tard sans modifier le moteur alimentaire historique.
create table if not exists public.food_speech_alias_overrides (
  id bigint generated by default as identity primary key,
  alias text not null,
  alias_normalized text generated always as (public.food_normalize(alias)) stored,
  locale text not null default 'fr-FR',
  dictionary_id uuid references public.food_dictionary(id) on delete cascade,
  ciqual_code text references public.ciqual_foods(code) on delete cascade,
  priority integer not null default 10,
  enabled boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint food_speech_alias_overrides_target_check
    check (num_nonnulls(dictionary_id,ciqual_code)=1),
  constraint food_speech_alias_overrides_alias_check
    check (length(alias_normalized)>=2),
  constraint food_speech_alias_overrides_priority_check
    check (priority between 0 and 1000)
);

create unique index if not exists food_speech_alias_dict_uidx
  on public.food_speech_alias_overrides(alias_normalized,locale,dictionary_id)
  where dictionary_id is not null;

create unique index if not exists food_speech_alias_ciqual_uidx
  on public.food_speech_alias_overrides(alias_normalized,locale,ciqual_code)
  where ciqual_code is not null;

create index if not exists food_speech_alias_lookup_idx
  on public.food_speech_alias_overrides(enabled,locale,alias_normalized,priority);

alter table public.food_speech_alias_overrides enable row level security;
drop policy if exists "food speech aliases authenticated read" on public.food_speech_alias_overrides;
drop policy if exists "food speech aliases admin manage" on public.food_speech_alias_overrides;
create policy "food speech aliases authenticated read" on public.food_speech_alias_overrides
  for select to authenticated using (enabled or public.is_admin());
create policy "food speech aliases admin manage" on public.food_speech_alias_overrides
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant select on public.food_speech_alias_overrides to authenticated;

create or replace function public.food_speech_alias_touch()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists food_speech_alias_touch_trigger on public.food_speech_alias_overrides;
create trigger food_speech_alias_touch_trigger
before update on public.food_speech_alias_overrides
for each row execute function public.food_speech_alias_touch();

-- ---------------------------------------------------------------------------
-- 2. LE DICTIONNAIRE APPREND AUTOMATIQUEMENT LES NOUVEAUX ALIAS TEXTE
-- ---------------------------------------------------------------------------
-- Important : on AJOUTE les alias à speech_aliases sans jamais supprimer les
-- variantes vocales saisies manuellement.
create or replace function public.food_dictionary_sync_speech_aliases()
returns trigger
language plpgsql
set search_path=public
as $$
begin
  select coalesce(array_agg(distinct v order by v),'{}'::text[])
  into new.speech_aliases
  from unnest(
    coalesce(new.speech_aliases,'{}'::text[])
    || coalesce(new.aliases,'{}'::text[])
    || array[new.canonical_name]
  ) as x(v)
  where nullif(trim(v),'') is not null;
  return new;
end;
$$;

drop trigger if exists food_dictionary_sync_speech_aliases_trigger on public.food_dictionary;
create trigger food_dictionary_sync_speech_aliases_trigger
before insert or update of canonical_name,aliases on public.food_dictionary
for each row execute function public.food_dictionary_sync_speech_aliases();

-- Backfill non destructif : conserve les alias V477 + ajoute les éventuels alias
-- catalogue apparus depuis.
with merged_aliases as (
  select
    d.id,
    coalesce(array_agg(distinct a.v order by a.v),'{}'::text[]) as merged
  from public.food_dictionary d
  cross join lateral unnest(
    coalesce(d.speech_aliases,'{}'::text[])
    || coalesce(d.aliases,'{}'::text[])
    || array[d.canonical_name]
  ) as a(v)
  where nullif(trim(a.v),'') is not null
  group by d.id
)
update public.food_dictionary d
set speech_aliases = m.merged
from merged_aliases m
where d.id = m.id
  and d.speech_aliases is distinct from m.merged;

-- ---------------------------------------------------------------------------
-- 3. PREMIERS ALIAS DE DICTÉE À TRÈS FORTE CONFIANCE
-- ---------------------------------------------------------------------------
-- On reste volontairement prudent : uniquement des graphies/transcriptions
-- plausibles et non ambiguës. Le catalogue pourra être enrichi après tests réels.
with seed(canonical_name,alias,priority,note) as (values
  ('Achu','atchou',0,'Transcription vocale fréquente de Achu'),
  ('Achu','atchu',1,'Variante phonétique de Achu'),
  ('Achu','achou',1,'Variante phonétique de Achu'),
  ('Achu / Taro sauce jaune','atchou',0,'Même identité alimentaire historique'),
  ('Achu / Taro sauce jaune','atchu',1,'Même identité alimentaire historique'),
  ('Achu / Taro sauce jaune','achou',1,'Même identité alimentaire historique'),
  ('Poulet DG','poulet d g',0,'La dictée peut séparer les initiales D et G'),
  ('Ndolè','n dole',3,'La dictée peut séparer le N du mot'),
  ('Attiéké','attieke',0,'Graphie sans accent'),
  ('Attiéké','atieke',2,'Variante de transcription'),
  ('Mikaté','mikate',0,'Graphie sans accent'),
  ('Mafé','mafe',0,'Graphie sans accent'),
  ('Thiéré','thiere',0,'Graphie sans accent'),
  ('Thiéboudiène / Ceebu jën','thieboudienne',0,'Graphie française courante'),
  ('Thiéboudiène / Ceebu jën','tieboudienne',1,'Variante courante'),
  ('Thiéboudiène / Ceebu jën','ceebu jen',0,'Graphie sans caractère spécial'),
  ('Jollof rice','jolof rice',2,'Variante de transcription possible')
)
insert into public.food_speech_alias_overrides(alias,locale,dictionary_id,priority,note)
select s.alias,'fr-FR',d.id,s.priority,s.note
from seed s
join public.food_dictionary d on d.canonical_name=s.canonical_name
where d.enabled
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- 4. NETTOYAGE LÉGER D'UNE PHRASE DICTÉE
-- ---------------------------------------------------------------------------
-- On ne « comprend » pas la phrase avec un LLM. On retire seulement les mots de
-- conversation/quantité les plus fréquents afin d'obtenir un fallback CIQUAL utile.
-- La résolution des plats culturels continue, elle, à scanner la phrase complète.
create or replace function public.food_speech_focus(value text)
returns text
language sql
immutable
parallel safe
as $$
  with tokens as (
    select w,ord
    from regexp_split_to_table(public.food_normalize(value),'[[:space:]]+')
         with ordinality as t(w,ord)
    where nullif(w,'') is not null
      and w not in (
        'j','je','jai','ai','mange','manges','mangee','manger','pris','prends','prendre',
        'viens','venir','vais','veux','voudrais','eu','avais','avait','pour',
        'du','de','la','le','les','des','un','une','d','l','au','aux',
        'avec','et','puis','ce','cette','ces','mon','ma','mes',
        'matin','midi','soir','aujourdhui','aujourd','hui',
        'deux','trois','quatre','cinq','six','sept','huit','neuf','dix',
        'demi','demie','moitie','peu','environ',
        'gramme','grammes','g','ml','cl','litre','litres',
        'bol','portion','portions','tranche','tranches','cuillere','cuilleres'
      )
  )
  select coalesce(string_agg(w,' ' order by ord),'') from tokens;
$$;

grant execute on function public.food_speech_focus(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. RÉSOLVEUR UNIVERSEL V2 : DICTIONNAIRE CULTUREL + CIQUAL
-- ---------------------------------------------------------------------------
-- AUCUNE fonction existante n'est remplacée. Le futur bouton « Le dire à Tee »
-- appellera resolve_food_speech_v2 uniquement lorsqu'on le branchera dans l'app.
--
-- Déduplication : lorsqu'un plat historique et une ligne CIQUAL partagent le même
-- ciqual_code (ex. les deux entrées Achu), ils deviennent UN SEUL candidat vocal.
create or replace function public.resolve_food_speech_v2(
  p_text text,
  p_limit integer default 8
)
returns table(
  food_ref text,
  source_kind text,
  dictionary_id uuid,
  multimodal_key text,
  ciqual_code text,
  canonical_name text,
  display_name text,
  country text,
  culture text,
  matched_term text,
  match_type text,
  confidence text,
  requires_confirmation boolean,
  match_rank integer
)
language sql
stable
security invoker
set search_path=public
as $$
  with q as (
    select
      public.food_normalize(left(coalesce(p_text,''),1000)) as v,
      public.food_speech_focus(left(coalesce(p_text,''),1000)) as focus
  ),
  dict_terms as (
    select d.id,d.multimodal_key,d.ciqual_code,d.canonical_name,d.display_name,d.country,d.culture,d.priority,
           d.normalized_name term_norm,d.canonical_name term_raw,'canonical'::text term_kind,0::integer kind_penalty
    from public.food_dictionary d
    where d.enabled and d.speech_enabled

    union all

    select d.id,d.multimodal_key,d.ciqual_code,d.canonical_name,d.display_name,d.country,d.culture,d.priority,
           public.food_normalize(a),a,'alias'::text,2::integer
    from public.food_dictionary d
    cross join lateral unnest(d.aliases) a
    where d.enabled and d.speech_enabled and length(public.food_normalize(a))>=2

    union all

    select d.id,d.multimodal_key,d.ciqual_code,d.canonical_name,d.display_name,d.country,d.culture,d.priority,
           public.food_normalize(a),a,'speech_alias'::text,1::integer
    from public.food_dictionary d
    cross join lateral unnest(d.speech_aliases) a
    where d.enabled and d.speech_enabled and length(public.food_normalize(a))>=2

    union all

    select d.id,d.multimodal_key,d.ciqual_code,d.canonical_name,d.display_name,d.country,d.culture,d.priority,
           o.alias_normalized,o.alias,'speech_override'::text,0::integer
    from public.food_speech_alias_overrides o
    join public.food_dictionary d on d.id=o.dictionary_id
    where o.enabled and o.locale='fr-FR' and d.enabled and d.speech_enabled
  ),
  dict_hits_raw as (
    select
      case when t.ciqual_code is not null then 'ciqual:'||t.ciqual_code else 'dict:'||coalesce(t.multimodal_key,t.id::text) end entity_key,
      'dictionary'::text source_kind,
      t.id dictionary_id,t.multimodal_key,t.ciqual_code,t.canonical_name,t.display_name,t.country,t.culture,
      t.term_raw matched_term,t.term_kind match_type,
      (
        case
          when q.v=t.term_norm then 0
          when q.focus<>'' and q.focus=t.term_norm then 1
          when position(' '||t.term_norm||' ' in ' '||q.v||' ')>0 then 8
          when q.focus<>'' and position(' '||t.term_norm||' ' in ' '||q.focus||' ')>0 then 9
          else 999
        end
        + t.kind_penalty
        + greatest(0,least(10,t.priority/20))
      )::integer rank_value
    from dict_terms t cross join q
    where length(t.term_norm)>=2
      and length(q.v)>=2
      and (
        q.v=t.term_norm
        or (q.focus<>'' and q.focus=t.term_norm)
        or position(' '||t.term_norm||' ' in ' '||q.v||' ')>0
        or (q.focus<>'' and position(' '||t.term_norm||' ' in ' '||q.focus||' ')>0)
      )
  ),
  component_hints as (
    select
      case when d.ciqual_code is not null then 'ciqual:'||d.ciqual_code else 'dict:'||coalesce(d.multimodal_key,d.id::text) end entity_key,
      'dictionary'::text source_kind,
      d.id dictionary_id,d.multimodal_key,d.ciqual_code,d.canonical_name,d.display_name,d.country,d.culture,
      comp.value matched_term,'component_hint'::text match_type,
      (75 + greatest(0,least(10,d.priority/20)))::integer rank_value
    from public.food_dictionary d
    cross join q
    cross join lateral jsonb_array_elements_text(
      case when jsonb_typeof(d.typical_components)='array' then d.typical_components else '[]'::jsonb end
    ) as comp(value)
    where d.enabled and d.speech_enabled
      and length(q.focus)>=3
      and public.food_normalize(comp.value)=q.focus
  ),
  ciqual_hits as (
    select
      'ciqual:'||c.code entity_key,
      'ciqual'::text source_kind,
      null::uuid dictionary_id,null::text multimodal_key,c.code ciqual_code,
      c.name canonical_name,c.name display_name,null::text country,null::text culture,
      c.name matched_term,'ciqual'::text match_type,
      (
        case
          when public.food_normalize(c.name)=q.focus then 3
          when q.focus<>'' and public.food_normalize(c.name) like q.focus||' %' then 10
          when q.focus<>'' and position(' '||q.focus||' ' in ' '||public.food_normalize(c.name)||' ')>0 then 22
          when q.focus<>'' and position(' '||q.focus||' ' in ' '||public.food_normalize(c.search_text)||' ')>0 then 34
          else 999
        end
        + case when coalesce(c.source,'CIQUAL')='CIQUAL' then 0 else 2 end
      )::integer rank_value
    from public.ciqual_foods c cross join q
    where length(q.focus)>=3
      and (
        public.food_normalize(c.name)=q.focus
        or public.food_normalize(c.name) like q.focus||' %'
        or position(' '||q.focus||' ' in ' '||public.food_normalize(c.name)||' ')>0
        or position(' '||q.focus||' ' in ' '||public.food_normalize(c.search_text)||' ')>0
      )
  ),
  ciqual_override_hits as (
    select
      'ciqual:'||c.code entity_key,
      'ciqual'::text source_kind,
      null::uuid dictionary_id,null::text multimodal_key,c.code ciqual_code,
      c.name canonical_name,c.name display_name,null::text country,null::text culture,
      o.alias matched_term,'speech_override'::text match_type,
      (
        case
          when q.v=o.alias_normalized then 0
          when q.focus<>'' and q.focus=o.alias_normalized then 1
          when position(' '||o.alias_normalized||' ' in ' '||q.v||' ')>0 then 8
          else 999
        end
        + greatest(0,least(10,o.priority/20))
      )::integer rank_value
    from public.food_speech_alias_overrides o
    join public.ciqual_foods c on c.code=o.ciqual_code
    cross join q
    where o.enabled and o.locale='fr-FR'
      and (
        q.v=o.alias_normalized
        or (q.focus<>'' and q.focus=o.alias_normalized)
        or position(' '||o.alias_normalized||' ' in ' '||q.v||' ')>0
      )
  ),
  all_hits as (
    select * from dict_hits_raw where rank_value<999
    union all
    select * from component_hints
    union all
    select * from ciqual_hits where rank_value<999
    union all
    select * from ciqual_override_hits where rank_value<999
  ),
  entity_dedup as (
    select distinct on (entity_key)
      entity_key,source_kind,dictionary_id,multimodal_key,ciqual_code,canonical_name,display_name,country,culture,
      matched_term,match_type,rank_value
    from all_hits
    order by entity_key,rank_value,(source_kind='dictionary') desc,length(coalesce(matched_term,'')) desc,canonical_name
  )
  select
    entity_key as food_ref,
    source_kind,dictionary_id,multimodal_key,ciqual_code,canonical_name,display_name,country,culture,
    matched_term,match_type,
    case
      when rank_value<=5 then 'exact'
      when rank_value<=20 then 'strong'
      when rank_value<=45 then 'probable'
      else 'possible'
    end as confidence,
    true as requires_confirmation,
    rank_value as match_rank
  from entity_dedup
  order by rank_value,
           case when source_kind='dictionary' then 0 else 1 end,
           length(coalesce(matched_term,'')) desc,
           display_name
  limit greatest(1,least(coalesce(p_limit,8),12));
$$;

grant execute on function public.resolve_food_speech_v2(text,integer) to authenticated;

commit;

-- ---------------------------------------------------------------------------
-- TESTS CONSEILLÉS APRÈS APPLICATION (lecture seule)
-- ---------------------------------------------------------------------------
-- select count(*) as alias_overrides from public.food_speech_alias_overrides where enabled;
-- select * from public.resolve_food_speech_v2('taro sauce jaune',8);
-- select * from public.resolve_food_speech_v2('taro',8);
-- select * from public.resolve_food_speech_v2('atchou',8);
-- select * from public.resolve_food_speech_v2('j''ai mangé du taro sauce jaune',8);
-- select * from public.resolve_food_speech_v2('attieke',8);
-- select * from public.resolve_food_speech_v2('poulet d g',8);
