-- MÉTHODE TEE V479 — Bébé TEE · Phase 3 « Comprendre les phrases »
-- Dépendance : V477 + V478B déjà appliquées.
--
-- OBJECTIF
-- Transformer une phrase dictée en éléments alimentaires structurés SANS IA cloud :
--   « J'ai mangé deux œufs, deux tartines de pain complet,
--      un demi avocat et un café au lait »
-- devient des segments avec quantité + unité + aliment candidat.
--
-- IMPORTANT
-- - ADDITIF UNIQUEMENT.
-- - Ne modifie aucun repas existant.
-- - Ne touche à aucun protocole, déblocage, XP, validation ou achat.
-- - N'écrit jamais automatiquement dans le Carnet.
-- - Toute proposition reste à confirmer par l'utilisatrice.
-- - Aucun appel IA / aucun stockage audio.

begin;

-- ---------------------------------------------------------------------------
-- 0. GARDE-FOU : Phase 2 doit être présente.
-- ---------------------------------------------------------------------------
do $$
begin
  if to_regprocedure('public.resolve_food_speech_v2(text,integer)') is null then
    raise exception 'V479 nécessite V478B : public.resolve_food_speech_v2(text,integer) est introuvable';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 1. LEXIQUE DES QUANTITÉS DICTÉES
-- ---------------------------------------------------------------------------
-- Administrable : on pourra enrichir « une douzaine », expressions régionales, etc.
create table if not exists public.food_speech_quantity_aliases (
  id bigint generated by default as identity primary key,
  alias text not null,
  alias_normalized text generated always as (public.food_normalize(alias)) stored,
  numeric_value numeric not null,
  priority integer not null default 10,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint food_speech_quantity_aliases_value_check check (numeric_value > 0 and numeric_value <= 1000),
  constraint food_speech_quantity_aliases_priority_check check (priority between 0 and 1000),
  constraint food_speech_quantity_aliases_alias_check check (length(alias_normalized) >= 1)
);

create unique index if not exists food_speech_quantity_aliases_uidx
  on public.food_speech_quantity_aliases(alias_normalized);

alter table public.food_speech_quantity_aliases enable row level security;
drop policy if exists "food speech quantity authenticated read" on public.food_speech_quantity_aliases;
drop policy if exists "food speech quantity admin manage" on public.food_speech_quantity_aliases;
create policy "food speech quantity authenticated read" on public.food_speech_quantity_aliases
  for select to authenticated using (enabled or public.is_admin());
create policy "food speech quantity admin manage" on public.food_speech_quantity_aliases
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant select on public.food_speech_quantity_aliases to authenticated;

insert into public.food_speech_quantity_aliases(alias,numeric_value,priority)
values
  ('un demi',0.5,0),('une demie',0.5,0),('une demi',0.5,1),('demi',0.5,2),('demie',0.5,2),
  ('un quart',0.25,0),('une quart',0.25,2),('quart',0.25,3),
  ('trois quarts',0.75,0),
  ('un',1,10),('une',1,10),
  ('deux',2,10),('trois',3,10),('quatre',4,10),('cinq',5,10),
  ('six',6,10),('sept',7,10),('huit',8,10),('neuf',9,10),('dix',10,10),
  ('onze',11,10),('douze',12,10),('treize',13,10),('quatorze',14,10),('quinze',15,10),
  ('seize',16,10),('dix sept',17,10),('dix huit',18,10),('dix neuf',19,10),('vingt',20,10),
  ('une douzaine',12,5)
on conflict (alias_normalized) do update
set numeric_value=excluded.numeric_value,
    priority=least(public.food_speech_quantity_aliases.priority,excluded.priority),
    enabled=true,
    updated_at=now();

-- ---------------------------------------------------------------------------
-- 2. LEXIQUE DES UNITÉS / PORTIONS
-- ---------------------------------------------------------------------------
-- base_unit/base_multiplier servent seulement aux unités métriques sûres.
-- Ex. 2 kg -> 2000 g ; 25 cl -> 250 ml.
-- Une « tranche », un « bol » ou une « poignée » ne sont JAMAIS convertis
-- automatiquement en grammes : confirmation nécessaire.
create table if not exists public.food_speech_unit_aliases (
  id bigint generated by default as identity primary key,
  alias text not null,
  alias_normalized text generated always as (public.food_normalize(alias)) stored,
  unit_code text not null,
  unit_label text not null,
  unit_kind text not null default 'household'
    check (unit_kind in ('mass','volume','household','piece','approximate')),
  base_unit text,
  base_multiplier numeric,
  priority integer not null default 10,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint food_speech_unit_aliases_multiplier_check check (base_multiplier is null or base_multiplier > 0),
  constraint food_speech_unit_aliases_priority_check check (priority between 0 and 1000),
  constraint food_speech_unit_aliases_alias_check check (length(alias_normalized) >= 1)
);

create unique index if not exists food_speech_unit_aliases_uidx
  on public.food_speech_unit_aliases(alias_normalized);
create index if not exists food_speech_unit_aliases_lookup_idx
  on public.food_speech_unit_aliases(enabled,priority,alias_normalized);

alter table public.food_speech_unit_aliases enable row level security;
drop policy if exists "food speech units authenticated read" on public.food_speech_unit_aliases;
drop policy if exists "food speech units admin manage" on public.food_speech_unit_aliases;
create policy "food speech units authenticated read" on public.food_speech_unit_aliases
  for select to authenticated using (enabled or public.is_admin());
create policy "food speech units admin manage" on public.food_speech_unit_aliases
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

grant select on public.food_speech_unit_aliases to authenticated;

insert into public.food_speech_unit_aliases
  (alias,unit_code,unit_label,unit_kind,base_unit,base_multiplier,priority)
values
  ('g','g','g','mass','g',1,0),('gramme','g','g','mass','g',1,1),('grammes','g','g','mass','g',1,1),
  ('kg','kg','kg','mass','g',1000,0),('kilo','kg','kg','mass','g',1000,1),('kilos','kg','kg','mass','g',1000,1),
  ('kilogramme','kg','kg','mass','g',1000,1),('kilogrammes','kg','kg','mass','g',1000,1),
  ('ml','ml','ml','volume','ml',1,0),('millilitre','ml','ml','volume','ml',1,1),('millilitres','ml','ml','volume','ml',1,1),
  ('cl','cl','cl','volume','ml',10,0),('centilitre','cl','cl','volume','ml',10,1),('centilitres','cl','cl','volume','ml',10,1),
  ('l','l','L','volume','ml',1000,0),('litre','l','L','volume','ml',1000,1),('litres','l','L','volume','ml',1000,1),
  ('cuillere a soupe','cas','c. à soupe','household',null,null,0),('cuilleres a soupe','cas','c. à soupe','household',null,null,0),
  ('c a soupe','cas','c. à soupe','household',null,null,1),
  ('cuillere a cafe','cac','c. à café','household',null,null,0),('cuilleres a cafe','cac','c. à café','household',null,null,0),
  ('c a cafe','cac','c. à café','household',null,null,1),
  ('tranche','tranche','tranche','household',null,null,1),('tranches','tranche','tranche','household',null,null,1),
  ('tartine','tartine','tartine','household',null,null,1),('tartines','tartine','tartine','household',null,null,1),
  ('portion','portion','portion','household',null,null,2),('portions','portion','portion','household',null,null,2),
  ('bol','bol','bol','household',null,null,2),('bols','bol','bol','household',null,null,2),
  ('tasse','tasse','tasse','household',null,null,2),('tasses','tasse','tasse','household',null,null,2),
  ('verre','verre','verre','household',null,null,2),('verres','verre','verre','household',null,null,2),
  ('poignee','poignee','poignée','household',null,null,2),('poignees','poignee','poignée','household',null,null,2),
  ('louche','louche','louche','household',null,null,2),('louches','louche','louche','household',null,null,2),
  ('pot','pot','pot','household',null,null,2),('pots','pot','pot','household',null,null,2),
  ('sachet','sachet','sachet','household',null,null,2),('sachets','sachet','sachet','household',null,null,2),
  ('piece','piece','pièce','piece',null,null,2),('pieces','piece','pièce','piece',null,null,2)
on conflict (alias_normalized) do update
set unit_code=excluded.unit_code,
    unit_label=excluded.unit_label,
    unit_kind=excluded.unit_kind,
    base_unit=excluded.base_unit,
    base_multiplier=excluded.base_multiplier,
    priority=least(public.food_speech_unit_aliases.priority,excluded.priority),
    enabled=true,
    updated_at=now();

-- ---------------------------------------------------------------------------
-- 3. NETTOYAGE DU DÉBUT D'UNE PHRASE / D'UN SEGMENT
-- ---------------------------------------------------------------------------
create or replace function public.food_speech_strip_intro(value text)
returns text
language sql
immutable
parallel safe
as $$
  with x as (
    select public.food_normalize(value) v
  ), y as (
    select regexp_replace(
      v,
      '^(ce matin |ce midi |ce soir |au petit dejeuner |au dejeuner |au diner |au souper )?(j ai mange|jai mange|j ai pris|jai pris|j ai bu|jai bu|je viens de manger|je viens de prendre|je mange|je prends|j ai|jai)[[:space:]]+',
      '',
      'i'
    ) v
    from x
  )
  select trim(regexp_replace(v,'^(mange|mangee|manger|pris|prendre|bu|boire)[[:space:]]+','','i'))
  from y;
$$;

grant execute on function public.food_speech_strip_intro(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 4. DÉCOUPAGE DE LA PHRASE EN MORCEAUX ALIMENTAIRES
-- ---------------------------------------------------------------------------
-- Les séparateurs restent volontairement simples et prévisibles : virgule,
-- point-virgule, retour ligne, « et », « avec », « puis », « ensuite ».
-- On ne touche pas aux données : cette fonction ne fait que produire des segments.
create or replace function public.food_speech_segments(value text)
returns table(item_index integer, raw_segment text)
language sql
immutable
parallel safe
as $$
  with prepared as (
    select regexp_replace(
      regexp_replace(coalesce(value,''),E'[\n\r,;]+',' | ','g'),
      '[[:space:]]+(et|avec|puis|ensuite)[[:space:]]+',
      ' | ',
      'gi'
    ) s
  ), pieces as (
    select trim(p) raw_segment, ord
    from prepared
    cross join lateral regexp_split_to_table(s,'\|') with ordinality as x(p,ord)
  )
  select row_number() over(order by ord)::integer item_index, raw_segment
  from pieces
  where length(public.food_normalize(raw_segment)) >= 2;
$$;

grant execute on function public.food_speech_segments(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. ANALYSE QUANTITÉ + UNITÉ D'UN SEGMENT
-- ---------------------------------------------------------------------------
create or replace function public.food_speech_parse_segment(p_segment text)
returns table(
  quantity_value numeric,
  quantity_text text,
  unit_code text,
  unit_label text,
  unit_kind text,
  base_quantity_value numeric,
  base_unit text,
  quantity_confidence text,
  quantity_requires_confirmation boolean,
  food_text text
)
language plpgsql
stable
security invoker
set search_path=public
as $$
declare
  v_work text;
  v_rest text;
  v_first_token text;
  v_qty record;
  v_unit record;
  v_quantity numeric;
  v_quantity_text text;
  v_unit_code text;
  v_unit_label text;
  v_unit_kind text;
  v_base_qty numeric;
  v_base_unit text;
  v_confidence text := 'unspecified';
  v_requires boolean := true;
begin
  v_work := public.food_speech_strip_intro(p_segment);
  v_work := trim(regexp_replace(v_work,'^(aussi|juste|simplement)[[:space:]]+','','i'));

  if nullif(v_work,'') is null then
    return;
  end if;

  -- Expressions volontairement approximatives : aucune quantité inventée.
  if v_work ~ '^(un peu|un petit peu)[[:space:]]+(de la|de l|du|des|de|d)[[:space:]]+' then
    v_quantity := null;
    v_quantity_text := 'un peu';
    v_confidence := 'approximate';
    v_requires := true;
    v_rest := regexp_replace(v_work,'^(un peu|un petit peu)[[:space:]]+(de la|de l|du|des|de|d)[[:space:]]+','','i');
  elsif v_work ~ '^quelques[[:space:]]+' then
    v_quantity := null;
    v_quantity_text := 'quelques';
    v_confidence := 'approximate';
    v_requires := true;
    v_rest := regexp_replace(v_work,'^quelques[[:space:]]+','','i');
  elsif v_work ~ '^plusieurs[[:space:]]+' then
    v_quantity := null;
    v_quantity_text := 'plusieurs';
    v_confidence := 'approximate';
    v_requires := true;
    v_rest := regexp_replace(v_work,'^plusieurs[[:space:]]+','','i');
  else
    v_rest := v_work;

    -- Nombre écrit en chiffres : « 150 g », « 2 oeufs ».
    v_first_token := split_part(v_rest,' ',1);
    if v_first_token ~ '^[0-9]+$' then
      v_quantity := v_first_token::numeric;
      v_quantity_text := v_first_token;
      v_confidence := 'exact';
      v_rest := trim(substr(v_rest,length(v_first_token)+1));
    else
      -- Nombre/fraction écrit en lettres : « deux », « un demi », etc.
      select q.alias_normalized,q.numeric_value,q.alias
      into v_qty
      from public.food_speech_quantity_aliases q
      where q.enabled
        and (v_rest=q.alias_normalized or v_rest like q.alias_normalized||' %')
      order by length(q.alias_normalized) desc,q.priority,q.id
      limit 1;

      if found then
        v_quantity := v_qty.numeric_value;
        v_quantity_text := v_qty.alias;
        v_confidence := 'interpreted';
        v_rest := trim(substr(v_rest,length(v_qty.alias_normalized)+1));
      end if;
    end if;
  end if;

  -- Unité la plus longue en tête : « cuillères à soupe » avant « cuillère ».
  select u.alias_normalized,u.unit_code,u.unit_label,u.unit_kind,u.base_unit,u.base_multiplier
  into v_unit
  from public.food_speech_unit_aliases u
  where u.enabled
    and (v_rest=u.alias_normalized or v_rest like u.alias_normalized||' %')
  order by length(u.alias_normalized) desc,u.priority,u.id
  limit 1;

  if found then
    v_unit_code := v_unit.unit_code;
    v_unit_label := v_unit.unit_label;
    v_unit_kind := v_unit.unit_kind;
    v_rest := trim(substr(v_rest,length(v_unit.alias_normalized)+1));
    v_rest := trim(regexp_replace(v_rest,'^(de la|de l|du|des|de|d)[[:space:]]+','','i'));

    if v_quantity is not null and v_unit.base_multiplier is not null then
      v_base_qty := v_quantity * v_unit.base_multiplier;
      v_base_unit := v_unit.base_unit;
      -- Une quantité métrique explicitement dictée peut être reprise telle quelle.
      v_requires := false;
    else
      v_requires := true;
    end if;
  else
    -- Articles/prépositions sans quantité : « du riz », « de l'avocat ».
    v_rest := trim(regexp_replace(v_rest,'^(de la|de l|du|des|de|d|le|la|les)[[:space:]]+','','i'));
    -- Une quantité en nombre de pièces (2 oeufs, 1 avocat...) doit rester confirmée
    -- car la conversion nutritionnelle en grammes dépend de l'aliment.
    if v_quantity is not null then
      v_requires := true;
    end if;
  end if;

  -- Petit nettoyage final sans inventer de contenu.
  v_rest := trim(regexp_replace(v_rest,'^(de la|de l|du|des|de|d)[[:space:]]+','','i'));

  return query select
    v_quantity,
    v_quantity_text,
    v_unit_code,
    v_unit_label,
    v_unit_kind,
    v_base_qty,
    v_base_unit,
    v_confidence,
    v_requires,
    nullif(v_rest,'');
end;
$$;

grant execute on function public.food_speech_parse_segment(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. RÉSOLVEUR DE PHRASE V3
-- ---------------------------------------------------------------------------
-- Une seule fonction pour la future UI :
--   phrase -> segments -> quantités -> resolve_food_speech_v2 -> alternatives.
-- Elle n'écrit rien. Le futur écran « Vérifie ce que j'ai compris » décidera ensuite.
create or replace function public.resolve_food_speech_phrase_v3(
  p_text text,
  p_limit_items integer default 12
)
returns table(
  item_index integer,
  raw_segment text,
  quantity_value numeric,
  quantity_text text,
  unit_code text,
  unit_label text,
  unit_kind text,
  base_quantity_value numeric,
  base_unit text,
  quantity_confidence text,
  quantity_requires_confirmation boolean,
  food_text text,
  food_ref text,
  source_kind text,
  dictionary_id uuid,
  multimodal_key text,
  ciqual_code text,
  canonical_name text,
  display_name text,
  country text,
  matched_term text,
  match_type text,
  food_confidence text,
  food_requires_confirmation boolean,
  overall_requires_confirmation boolean,
  resolution_status text,
  alternatives jsonb
)
language sql
stable
security invoker
set search_path=public
as $$
  with seg as (
    select *
    from public.food_speech_segments(left(coalesce(p_text,''),2000))
    where item_index <= greatest(1,least(coalesce(p_limit_items,12),20))
  ), parsed as (
    select
      s.item_index,s.raw_segment,
      p.quantity_value,p.quantity_text,p.unit_code,p.unit_label,p.unit_kind,
      p.base_quantity_value,p.base_unit,p.quantity_confidence,p.quantity_requires_confirmation,p.food_text
    from seg s
    cross join lateral public.food_speech_parse_segment(s.raw_segment) p
    where p.food_text is not null and length(p.food_text)>=2
  ), query_variants as (
    select p.*,p.food_text query_text,0::integer variant_penalty
    from parsed p

    union all

    -- Fallback pluriel très prudent : « oeufs » -> « oeuf », « avocats » -> « avocat ».
    select p.*,regexp_replace(p.food_text,'s$','') query_text,4::integer variant_penalty
    from parsed p
    where length(p.food_text)>=4 and p.food_text ~ 's$'
  ), candidate_rows as (
    select
      q.item_index,q.raw_segment,q.quantity_value,q.quantity_text,q.unit_code,q.unit_label,q.unit_kind,
      q.base_quantity_value,q.base_unit,q.quantity_confidence,q.quantity_requires_confirmation,q.food_text,
      r.food_ref,r.source_kind,r.dictionary_id,r.multimodal_key,r.ciqual_code,r.canonical_name,r.display_name,
      r.country,r.matched_term,r.match_type,r.confidence food_confidence,r.requires_confirmation food_requires_confirmation,
      (r.match_rank + q.variant_penalty)::integer candidate_score
    from query_variants q
    left join lateral public.resolve_food_speech_v2(q.query_text,5) r on true
  ), candidate_dedup as (
    select distinct on (item_index,food_ref)
      *
    from candidate_rows
    order by item_index,food_ref,candidate_score nulls last,(source_kind='dictionary') desc,display_name
  ), ranked as (
    select
      c.*,
      row_number() over(
        partition by item_index
        order by candidate_score nulls last,
                 case when source_kind='dictionary' then 0 else 1 end,
                 display_name nulls last
      )::integer candidate_rank
    from candidate_dedup c
  ), grouped as (
    select
      item_index,
      max(raw_segment) raw_segment,
      max(quantity_value) quantity_value,
      max(quantity_text) quantity_text,
      max(unit_code) unit_code,
      max(unit_label) unit_label,
      max(unit_kind) unit_kind,
      max(base_quantity_value) base_quantity_value,
      max(base_unit) base_unit,
      max(quantity_confidence) quantity_confidence,
      bool_or(quantity_requires_confirmation) quantity_requires_confirmation,
      max(food_text) food_text,
      max(food_ref) filter (where candidate_rank=1 and food_ref is not null) food_ref,
      max(source_kind) filter (where candidate_rank=1 and food_ref is not null) source_kind,
      (array_agg(dictionary_id order by candidate_score nulls last) filter (where candidate_rank=1 and food_ref is not null))[1] dictionary_id,
      max(multimodal_key) filter (where candidate_rank=1 and food_ref is not null) multimodal_key,
      max(ciqual_code) filter (where candidate_rank=1 and food_ref is not null) ciqual_code,
      max(canonical_name) filter (where candidate_rank=1 and food_ref is not null) canonical_name,
      max(display_name) filter (where candidate_rank=1 and food_ref is not null) display_name,
      max(country) filter (where candidate_rank=1 and food_ref is not null) country,
      max(matched_term) filter (where candidate_rank=1 and food_ref is not null) matched_term,
      max(match_type) filter (where candidate_rank=1 and food_ref is not null) match_type,
      max(food_confidence) filter (where candidate_rank=1 and food_ref is not null) food_confidence,
      coalesce(bool_or(food_requires_confirmation) filter (where candidate_rank=1 and food_ref is not null),true) food_requires_confirmation,
      coalesce(
        jsonb_agg(
          jsonb_build_object(
            'food_ref',food_ref,
            'display_name',display_name,
            'canonical_name',canonical_name,
            'country',country,
            'confidence',food_confidence,
            'match_type',match_type,
            'matched_term',matched_term,
            'source_kind',source_kind,
            'ciqual_code',ciqual_code,
            'dictionary_id',dictionary_id,
            'multimodal_key',multimodal_key,
            'match_rank',candidate_score
          )
          order by candidate_score nulls last,display_name
        ) filter (where food_ref is not null and candidate_rank<=4),
        '[]'::jsonb
      ) alternatives
    from ranked
    group by item_index
  )
  select
    g.item_index,g.raw_segment,g.quantity_value,g.quantity_text,g.unit_code,g.unit_label,g.unit_kind,
    g.base_quantity_value,g.base_unit,g.quantity_confidence,g.quantity_requires_confirmation,g.food_text,
    g.food_ref,g.source_kind,g.dictionary_id,g.multimodal_key,g.ciqual_code,g.canonical_name,g.display_name,
    g.country,g.matched_term,g.match_type,
    coalesce(g.food_confidence,'unresolved') food_confidence,
    g.food_requires_confirmation,
    true overall_requires_confirmation,
    case when g.food_ref is null then 'needs_search' else 'resolved_candidate' end resolution_status,
    g.alternatives
  from grouped g
  order by g.item_index;
$$;

grant execute on function public.resolve_food_speech_phrase_v3(text,integer) to authenticated;

-- ---------------------------------------------------------------------------
-- 7. FORMAT JSON COMPACT POUR LA FUTURE INTERFACE « LE DIRE À TEE »
-- ---------------------------------------------------------------------------
-- Permettra plus tard UN SEUL RPC après transcription locale de l'iPhone.
create or replace function public.resolve_food_speech_phrase_v3_json(
  p_text text,
  p_limit_items integer default 12
)
returns jsonb
language sql
stable
security invoker
set search_path=public
as $$
  with items as (
    select * from public.resolve_food_speech_phrase_v3(p_text,p_limit_items)
  )
  select jsonb_build_object(
    'input',coalesce(p_text,''),
    'item_count',count(*),
    'all_foods_resolved',coalesce(bool_and(food_ref is not null),false),
    'requires_confirmation',true,
    'items',coalesce(jsonb_agg(to_jsonb(items) order by item_index),'[]'::jsonb)
  )
  from items;
$$;

grant execute on function public.resolve_food_speech_phrase_v3_json(text,integer) to authenticated;

commit;

-- ---------------------------------------------------------------------------
-- TESTS CONSEILLÉS APRÈS APPLICATION — LECTURE SEULE
-- ---------------------------------------------------------------------------
-- 1. Phrase complète classique
-- select * from public.resolve_food_speech_phrase_v3(
--   'J''ai mangé deux œufs, deux tartines de pain complet, un demi avocat et un café au lait',12
-- );
--
-- 2. Culturel + accompagnement
-- select * from public.resolve_food_speech_phrase_v3(
--   'J''ai mangé du taro sauce jaune avec du boeuf',12
-- );
--
-- 3. Quantité approximative : aucune valeur n'est inventée
-- select * from public.resolve_food_speech_phrase_v3(
--   'J''ai mangé du ndolé avec deux plantains et un peu de riz',12
-- );
--
-- 4. Quantités métriques explicites
-- select * from public.resolve_food_speech_phrase_v3(
--   'J''ai mangé 150 g de riz et 120 g de poulet',12
-- );
--
-- 5. Format JSON destiné à la future UI
-- select public.resolve_food_speech_phrase_v3_json(
--   'J''ai mangé deux oeufs et une tartine de pain complet',12
-- );
