let mtSupabase=null;
function supabaseReady(){const c=window.MT_CONFIG||{};return c.USE_SUPABASE&&c.SUPABASE_URL&&c.SUPABASE_ANON_KEY}
function initSupabase(){if(!supabaseReady())return null;if(window.supabase&&!mtSupabase){mtSupabase=window.supabase.createClient(window.MT_CONFIG.SUPABASE_URL,window.MT_CONFIG.SUPABASE_ANON_KEY)}return mtSupabase}
async function mtUser(){const c=initSupabase();if(c){const{data}=await c.auth.getUser();return data.user}return null}
async function mtSignUp(email,password,fullName){const c=initSupabase();const{data,error}=await c.auth.signUp({email,password,options:{data:{full_name:fullName}}});if(error)throw error;return data.user}
async function mtSignIn(email,password){const c=initSupabase();const{data,error}=await c.auth.signInWithPassword({email,password});if(error)throw error;return data.user}
async function mtSignOut(){const c=initSupabase();if(c)await c.auth.signOut()}
async function mtIsAdmin(){const u=await mtUser();if(!u)return false;return (window.MT_CONFIG.ADMIN_EMAILS||[]).map(x=>x.toLowerCase()).includes((u.email||'').toLowerCase())}
async function mtSetting(key){const c=initSupabase();if(c){const{data}=await c.from('app_settings').select('value').eq('key',key).maybeSingle();if(data?.value)return data.value}return localStorage.getItem('mt_'+key)}
async function mtSetSetting(key,value){localStorage.setItem('mt_'+key,value);const c=initSupabase();if(c){const{error}=await c.from('app_settings').upsert({key,value});if(error)throw error}}
async function mtSections(){const c=initSupabase();if(c){const{data,error}=await c.from('sections').select('*').eq('is_visible',true).order('position');if(!error&&data?.length)return data}return window.MT_FALLBACK.sections}
async function mtPosts(){const c=initSupabase();if(c){const{data,error}=await c.from('journal_posts').select('*').eq('is_published',true).order('created_at',{ascending:false});if(!error&&data)return data}return window.MT_FALLBACK.posts}
async function mtProtocols(cat){const c=initSupabase();if(c){let q=c.from('protocols').select('*').eq('is_active',true).order('created_at',{ascending:false});if(cat)q=q.eq('category',cat);const{data,error}=await q;if(!error&&data)return data}return window.MT_FALLBACK.protocols.filter(p=>!cat||p.category===cat)}
async function mtProtocol(id){const c=initSupabase();if(c){const{data,error}=await c.from('protocols').select('*').eq('id',id).maybeSingle();if(!error&&data)return data}return window.MT_FALLBACK.protocols.find(p=>p.id===id)}
async function mtHasProtocol(id){const u=await mtUser();if(!u)return false;const c=initSupabase();const{data}=await c.from('purchases').select('*').eq('user_id',u.id).eq('protocol_id',id).eq('status','active').maybeSingle();if(!data)return false;if(data.access_expires_at&&new Date(data.access_expires_at)<new Date())return false;return true}
async function mtPurchases(){const u=await mtUser();if(!u)return[];const c=initSupabase();const{data,error}=await c.from('purchases').select('*, protocols(*)').eq('user_id',u.id).order('created_at',{ascending:false});return error?[]:(data||[])}
async function mtProtocolFiles(id){const c=initSupabase();const{data,error}=await c.from('protocol_files').select('*').eq('protocol_id',id).order('sort_order');return error?[]:(data||[])}
async function mtSignedUrl(path){const c=initSupabase();const{data,error}=await c.storage.from('guide-pdfs').createSignedUrl(path,600);if(error)throw error;return data.signedUrl}
async function mtUpload(file,folder){const c=initSupabase();const path=`${folder}/${Date.now()}-${file.name}`;const{error}=await c.storage.from('guide-pdfs').upload(path,file,{upsert:true});if(error)throw error;return path}
async function mtCreatePost(payload,files){const c=initSupabase();const u=await mtUser();const media_urls=[],media_types=[];for(const f of files||[]){media_urls.push(await mtUpload(f,'journal'));media_types.push(f.type.startsWith('video')?'video':'image')}const{error}=await c.from('journal_posts').insert({...payload,media_urls,media_types,created_by:u.id});if(error)throw error}
async function mtCreateProtocol(payload,imageFile){const c=initSupabase();const u=await mtUser();let image_url='';if(imageFile)image_url=await mtUpload(imageFile,'protocol-images');const{error}=await c.from('protocols').upsert({...payload,image_url,created_by:u.id});if(error)throw error}
async function mtAddProtocolFile(protocolId,title,file,type,description){const c=initSupabase();const path=await mtUpload(file,`protocols/${protocolId}`);const{error}=await c.from('protocol_files').insert({protocol_id:protocolId,title,file_type:type,storage_path:path,description});if(error)throw error}
async function mtCreateSection(payload){const c=initSupabase();const{error}=await c.from('sections').upsert(payload);if(error)throw error}
async function mtDemoBuy(protocol){const u=await mtUser();const c=initSupabase();const expires=new Date(Date.now()+(protocol.duration_days||5)*86400000).toISOString();const{error}=await c.from('purchases').insert({user_id:u.id,protocol_id:protocol.id,amount:protocol.price,currency:'EUR',access_expires_at:expires,status:'active'});if(error)throw error}
