-- V331 — Carnet alimentaire / Adapter mon repas
-- N'altère aucune table d'achats, StoreKit, Stripe, protocoles ou déblocages.

create table if not exists public.ciqual_foods (
  code text primary key,
  name text not null,
  search_text text not null,
  kcal_100g numeric,
  protein_100g numeric,
  fat_100g numeric,
  carbs_100g numeric,
  fiber_100g numeric,
  salt_100g numeric,
  source text default 'CIQUAL',
  updated_at timestamptz default now()
);

create index if not exists ciqual_foods_search_fts_idx
  on public.ciqual_foods using gin (to_tsvector('simple', search_text));
create index if not exists ciqual_foods_name_idx on public.ciqual_foods(name);

alter table public.ciqual_foods enable row level security;
drop policy if exists "ciqual authenticated read" on public.ciqual_foods;
create policy "ciqual authenticated read" on public.ciqual_foods
  for select to authenticated using (true);

create table if not exists public.food_meals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  meal_date date not null default current_date,
  meal_type text not null check (meal_type in ('breakfast','lunch','snack','dinner')),
  meal_time time,
  description text,
  photo_path text,
  source_recipe_id text,
  source_recipe_title text,
  source_recipe_image_url text,
  kcal_total numeric default 0,
  protein_total numeric default 0,
  fat_total numeric default 0,
  carbs_total numeric default 0,
  fiber_total numeric default 0,
  salt_total numeric default 0,
  energy_after smallint check (energy_after between 1 and 10),
  digestion_after smallint check (digestion_after between 1 and 10),
  satiety_after smallint check (satiety_after between 1 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists food_meals_user_date_idx on public.food_meals(user_id,meal_date desc);
create index if not exists food_meals_user_type_date_idx on public.food_meals(user_id,meal_date,meal_type);
alter table public.food_meals enable row level security;
drop policy if exists "food meals own read" on public.food_meals;
drop policy if exists "food meals own insert" on public.food_meals;
drop policy if exists "food meals own update" on public.food_meals;
drop policy if exists "food meals own delete" on public.food_meals;
create policy "food meals own read" on public.food_meals for select to authenticated using (auth.uid()=user_id);
create policy "food meals own insert" on public.food_meals for insert to authenticated with check (auth.uid()=user_id);
create policy "food meals own update" on public.food_meals for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "food meals own delete" on public.food_meals for delete to authenticated using (auth.uid()=user_id);

create table if not exists public.food_meal_items (
  id bigint generated by default as identity primary key,
  meal_id uuid not null references public.food_meals(id) on delete cascade,
  sort_order integer default 0,
  ciqual_code text references public.ciqual_foods(code) on delete set null,
  food_name text not null,
  quantity_g numeric not null default 100,
  kcal_100g numeric default 0,
  protein_100g numeric default 0,
  fat_100g numeric default 0,
  carbs_100g numeric default 0,
  fiber_100g numeric default 0,
  salt_100g numeric default 0,
  kcal numeric default 0,
  protein numeric default 0,
  fat numeric default 0,
  carbs numeric default 0,
  fiber numeric default 0,
  salt numeric default 0,
  created_at timestamptz default now()
);
create index if not exists food_meal_items_meal_idx on public.food_meal_items(meal_id,sort_order);
alter table public.food_meal_items enable row level security;
drop policy if exists "food meal items own read" on public.food_meal_items;
drop policy if exists "food meal items own insert" on public.food_meal_items;
drop policy if exists "food meal items own update" on public.food_meal_items;
drop policy if exists "food meal items own delete" on public.food_meal_items;
create policy "food meal items own read" on public.food_meal_items for select to authenticated using (exists(select 1 from public.food_meals m where m.id=meal_id and m.user_id=auth.uid()));
create policy "food meal items own insert" on public.food_meal_items for insert to authenticated with check (exists(select 1 from public.food_meals m where m.id=meal_id and m.user_id=auth.uid()));
create policy "food meal items own update" on public.food_meal_items for update to authenticated using (exists(select 1 from public.food_meals m where m.id=meal_id and m.user_id=auth.uid())) with check (exists(select 1 from public.food_meals m where m.id=meal_id and m.user_id=auth.uid()));
create policy "food meal items own delete" on public.food_meal_items for delete to authenticated using (exists(select 1 from public.food_meals m where m.id=meal_id and m.user_id=auth.uid()));

create table if not exists public.food_adaptations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  meal_id uuid references public.food_meals(id) on delete set null,
  meal_date date not null default current_date,
  input_text text not null,
  goal text default 'equilibre',
  photo_path text,
  parsed_items jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  why jsonb not null default '[]'::jsonb,
  status text not null default 'proposed' check(status in ('proposed','adopted','kept')),
  decided_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists food_adaptations_user_date_idx on public.food_adaptations(user_id,meal_date desc);
alter table public.food_adaptations enable row level security;
drop policy if exists "food adaptations own read" on public.food_adaptations;
drop policy if exists "food adaptations own insert" on public.food_adaptations;
drop policy if exists "food adaptations own update" on public.food_adaptations;
drop policy if exists "food adaptations own delete" on public.food_adaptations;
create policy "food adaptations own read" on public.food_adaptations for select to authenticated using (auth.uid()=user_id);
create policy "food adaptations own insert" on public.food_adaptations for insert to authenticated with check (auth.uid()=user_id);
create policy "food adaptations own update" on public.food_adaptations for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "food adaptations own delete" on public.food_adaptations for delete to authenticated using (auth.uid()=user_id);

-- Bucket privé : une seule image stockée, réutilisée par les vues du repas.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('food-media','food-media',false,3145728,array['image/webp','image/jpeg','image/png'])
on conflict(id) do update set public=false,file_size_limit=3145728,allowed_mime_types=array['image/webp','image/jpeg','image/png'];

drop policy if exists "food media own read" on storage.objects;
drop policy if exists "food media own insert" on storage.objects;
drop policy if exists "food media own update" on storage.objects;
drop policy if exists "food media own delete" on storage.objects;
create policy "food media own read" on storage.objects for select to authenticated using (bucket_id='food-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "food media own insert" on storage.objects for insert to authenticated with check (bucket_id='food-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "food media own update" on storage.objects for update to authenticated using (bucket_id='food-media' and (storage.foldername(name))[1]=auth.uid()::text) with check (bucket_id='food-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "food media own delete" on storage.objects for delete to authenticated using (bucket_id='food-media' and (storage.foldername(name))[1]=auth.uid()::text);

-- Résumé compact réutilisable par Mon Équilibre sans charger l'historique alimentaire complet.
create or replace function public.food_day_balance_summary(target_date date default current_date)
returns jsonb
language sql
stable
security invoker
set search_path=public
as $$
  select jsonb_build_object(
    'meal_count', count(*),
    'protein_total', coalesce(round(sum(protein_total)::numeric,1),0),
    'fiber_total', coalesce(round(sum(fiber_total)::numeric,1),0),
    'energy_after', case when count(energy_after)>0 then round(avg(energy_after)::numeric,1) else null end,
    'digestion_after', case when count(digestion_after)>0 then round(avg(digestion_after)::numeric,1) else null end,
    'satiety_after', case when count(satiety_after)>0 then round(avg(satiety_after)::numeric,1) else null end
  )
  from public.food_meals
  where user_id=auth.uid() and meal_date=target_date;
$$;
grant execute on function public.food_day_balance_summary(date) to authenticated;
