
/* MÉTHODE TEE V14 — Private Club Luxe Layer */
(function(){
  const state={settings:{club_name:'Méthode Tee Club',hero_subtitle:'Journal privé · Nutrition · Plantes · Bien-être',ambiance:'botanical',quote:'Ton corps sait. Accompagne-le.',show_stories:true,show_private_drops:true},member:null,capsules:[],drops:[]};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const safe=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  async function fetchSettings(){try{const c=initSupabase&&initSupabase(); if(!c)return state.settings; const {data}=await c.from('club_settings').select('*').limit(1).maybeSingle(); if(data)state.settings={...state.settings,...data};}catch(e){} return state.settings;}
  async function fetchMember(){try{const c=initSupabase&&initSupabase(), u=await mtGetUser(); if(!c||!u)return null; const {data}=await c.from('member_profiles').select('*').eq('user_id',u.id).maybeSingle(); state.member=data||{level:'Green',points:0,streak:0,badge:'🌿'};}catch(e){state.member={level:'Green',points:0,streak:0,badge:'🌿'}} return state.member;}
  async function fetchCapsules(){try{const c=initSupabase&&initSupabase(); if(c){const {data}=await c.from('club_capsules').select('*').eq('active',true).order('sort_order',{ascending:true}).limit(12); if(data&&data.length)state.capsules=data;}}catch(e){} if(!state.capsules.length)state.capsules=[{title:'Routine du jour',emoji:'🌿',type:'Routine',accent:'green'},{title:'Conseil privé',emoji:'✨',type:'Tip',accent:'gold'},{title:'Drop exclusif',emoji:'🔒',type:'Drop',accent:'dark'},{title:'Mindset',emoji:'🧘🏽‍♀️',type:'Mindset',accent:'soft'}]; return state.capsules;}
  async function fetchDrops(){try{const c=initSupabase&&initSupabase(); if(c){const {data}=await c.from('private_drops').select('*').eq('active',true).order('created_at',{ascending:false}).limit(5); state.drops=data||[];}}catch(e){} return state.drops;}
  function ambiance(s){if($('#ambianceLayer'))return; let d=document.createElement('div'); d.id='ambianceLayer'; d.className='ambiance-layer ambiance-'+(s.ambiance||'botanical'); d.innerHTML='<div class="orb orb-a"></div><div class="orb orb-b"></div><div class="grain"></div>'; document.body.prepend(d);}
  function loader(){let d=document.createElement('div'); d.className='luxury-loader'; d.innerHTML='<img src="assets/brand-logo.png"><span>Ouverture du club privé</span>'; document.body.appendChild(d); setTimeout(()=>d.classList.add('hide'),650); setTimeout(()=>d.remove(),1100)}
  function transitions(){document.body.classList.add('page-entered'); document.addEventListener('click',e=>{let a=e.target.closest('a[href]'); if(!a)return; let h=a.getAttribute('href'); if(!h||h.startsWith('http')||h.startsWith('#')||a.target==='_blank')return; e.preventDefault(); document.body.classList.add('page-leaving'); setTimeout(()=>location.href=h,170);});}
  function touch(){document.addEventListener('pointerdown',e=>{let c=e.target.closest('.post-card,.protocol-card,.content-card,.mini-card,.library-category,.main-cta,.navbar a'); if(c)c.classList.add('is-pressing')}); ['pointerup','pointercancel'].forEach(ev=>document.addEventListener(ev,()=>$$('.is-pressing').forEach(x=>x.classList.remove('is-pressing'))));}
  function toasts(){window.mtToast=(m,t='success')=>{let w=$('#toastLayer'); if(!w){w=document.createElement('div'); w.id='toastLayer'; w.className='toast-layer'; document.body.appendChild(w)} let n=document.createElement('div'); n.className='premium-toast '+t; n.innerHTML='<b>'+(t==='error'?'⚠️':'✨')+'</b><span>'+safe(m)+'</span>'; w.appendChild(n); requestAnimationFrame(()=>n.classList.add('show')); setTimeout(()=>{n.classList.remove('show');setTimeout(()=>n.remove(),350)},3200)}}
  async function enhanceHome(){let feed=$('#homeFeed'), hero=$('.home-hero'); if(!feed&&!hero)return; let s=await fetchSettings(), m=await fetchMember(), caps=await fetchCapsules(), drops=await fetchDrops(); ambiance(s); if(hero&&!$('#clubIntro')){let x=document.createElement('section'); x.id='clubIntro'; x.className='club-intro reveal visible'; x.innerHTML='<div class="club-eyebrow">'+safe(s.club_name)+'</div><h2>'+safe(s.quote)+'</h2><p>'+safe(s.hero_subtitle)+'</p><div class="member-strip"><span>'+safe(m?.badge||'🌿')+'</span><strong>'+safe(m?.level||'Green')+' Member</strong><em>'+Number(m?.streak||0)+' jours de présence</em></div>'; hero.appendChild(x)} if(s.show_stories&&feed&&!$('#storyRail')){let r=document.createElement('section'); r.id='storyRail'; r.className='story-rail reveal visible'; r.innerHTML=caps.map(c=>'<button class="story-bubble accent-'+safe(c.accent||'green')+'" onclick="mtToast(\''+safe(c.title)+'\')"><span>'+safe(c.emoji||'✦')+'</span><b>'+safe(c.title)+'</b><small>'+safe(c.type||'Privé')+'</small></button>').join(''); feed.parentNode.insertBefore(r,feed)} if(s.show_private_drops&&drops.length&&feed&&!$('#privateDrops')){let b=document.createElement('section'); b.id='privateDrops'; b.className='private-drops reveal visible'; b.innerHTML='<div class="kicker">Drops privés</div><div class="drop-grid">'+drops.map(d=>'<article class="drop-card"><span>'+safe(d.emoji||'🔒')+'</span><h3>'+safe(d.title)+'</h3><p>'+safe(d.description||'')+'</p>'+(d.url?'<a href="'+safe(d.url)+'" target="_blank">Ouvrir</a>':'')+'</article>').join('')+'</div>'; feed.parentNode.insertBefore(b,feed)}}
  function posts(){ $$('.post-card').forEach((c,i)=>{if(c.dataset.v14)return; c.dataset.v14='1'; c.style.setProperty('--delay',Math.min(i*60,420)+'ms'); if(!c.querySelector('.post-actions')){let a=document.createElement('div'); a.className='post-actions'; a.innerHTML='<button onclick="mtToast(\'Ajouté aux favoris\')">♡ Favori</button><button onclick="mtToast(\'Routine sauvegardée\')">＋ Routine</button>'; c.appendChild(a)}})}
  function observe(){new MutationObserver(()=>posts()).observe(document.body,{childList:true,subtree:true})}
  document.addEventListener('DOMContentLoaded',()=>{loader();transitions();touch();toasts();observe();setTimeout(enhanceHome,450);setTimeout(posts,700)});
})();
