const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const catalog=JSON.parse(fs.readFileSync(path.join(root,'data/v48941/catalogue_300_repas_v48941.json'),'utf8'));
const js=fs.readFileSync(path.join(root,'scripts/tee-next.js'),'utf8');
const sql=fs.readFileSync(path.join(root,'supabase/V48941_CATALOGUE_CULINAIRE_TEE_VALIDE.sql'),'utf8');
function ok(cond,msg){if(!cond)throw new Error(msg)}
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
ok(catalog.length===300,'catalogue != 300');
ok(new Set(catalog.map(x=>norm(x.title))).size===300,'titres dupliqués');
ok(new Set(catalog.map(x=>x.semantic_signature)).size===300,'signatures dupliquées');
ok(catalog.filter(x=>x.discovery_level===0).length===258,'niveau 0 inattendu');
ok(catalog.filter(x=>x.discovery_level===1).length===28,'niveau 1 inattendu');
ok(catalog.filter(x=>x.discovery_level===2).length===14,'niveau 2 inattendu');
ok(catalog.filter(x=>x.discovery_level===2).every(x=>x.cultural_specific===true),'niveau 2 non spécifique');
ok(catalog.filter(x=>x.auto_publish_policy==='existing_strict_preferred').length===9,'doublons stricts inattendus');
ok(catalog.filter(x=>x.auto_publish_policy==='manual_specific').every(x=>x.discovery_level===2),'manual_specific hors niveau2');
const get=code=>catalog.find(x=>x.meal_code===code);
ok(get('TEE-MEAL-278').components.find(x=>/haricots verts/i.test(x.name)).role==='vegetable','Gado-gado haricots verts');
ok(get('TEE-MEAL-291').components.find(x=>/haricots verts/i.test(x.name)).role==='vegetable','Niçoise haricots verts');
ok(get('TEE-MEAL-266').components.find(x=>/paneer/i.test(x.name)).role==='dairy_protein','Paneer role');
ok(!get('TEE-MEAL-298').components.some(x=>/ ou /i.test(x.name)),'Moussaka ambiguë');
ok(!get('TEE-MEAL-293').components.some(x=>/pomme de terre/i.test(x.name)),'Cassoulet + pomme de terre');
ok(/mt_planner_curated_catalog_v2/.test(js),'RPC curated v2 frontend absent');
ok(/buildCuratedCandidatesV48941/.test(js),'builder curated absent');
ok(!/const dyn=await buildDynamicCiqualCandidatesV4891\(/.test(js),'assembleur libre encore appelé');
ok(/rawAssemblyFallbackUsed:false/.test(js),'debug raw fallback non verrouillé');
ok(/mt_curated_meal_components_v2/.test(sql),'table composants v2 absente');
ok(/resolution_status='resolved_high'/.test(sql),'publication forte absente');
ok(/level_2_requires_manual_review/.test(sql),'guard culture niveau2 absent');
console.log(JSON.stringify({status:'ok',total:catalog.length,level0:258,level1:28,level2:14,freeAssemblyRuntime:false},null,2));
