'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const raw=fs.readFileSync(path.join(root,'scripts/tee-next.js'),'utf8');
const context={console,URLSearchParams,location:{search:''},window:{},document:{addEventListener(){}}};
vm.createContext(context);
vm.runInContext(raw.replace("document.addEventListener('DOMContentLoaded',init);",'globalThis.T={plannerWeekReasonsV489653,plannerWhyHtmlV489652,plannerRenderInteractiveV4896};'),context);
const T=context.T;
const memory={active:false,countryMap:new Map(),recentTitles:new Set(),tokenMap:new Map(),categoryMap:new Map(),familiarIds:new Set()};
const meal=(id,protein='poultry',starch='rice',cuisine='western_europe')=>({recipe_id:id,title:id,_curatedMeal:true,_dynamicCiqual:true,_memoryRank:1,_memoryAffinity:3,_traits:{protein_family:protein,starch_family:starch,cuisine_family:cuisine}});
const day=recipe=>({recipe,leftover:false,restaurant:false});
const plan=[day(meal('a')),day(meal('b')),day(meal('c'))];
const reasons=T.plannerWeekReasonsV489653(plan,memory);
assert(reasons[0].includes('fil culinaire'));
assert.equal(reasons[1],'');
assert.equal(reasons[2],'');
assert.equal(T.plannerWhyHtmlV489652(plan[1].recipe,{index:1,weekReasons:reasons}), '');
assert.equal(T.plannerWeekReasonsV489653([day(meal('unknown','unknown','unknown','tee_general'))],memory)[0],'');
const varied=[...plan,day(meal('fish','fish','quinoa','tee_general'))];
const distinct=T.plannerWeekReasonsV489653(varied,memory)[3];
assert(distinct.includes('protéine différente'));
assert(distinct.includes('féculent moins présent'));
const leftover=[day(meal('prep')), {recipe:meal('prep'),leftover:true}, {restaurant:true}];
assert(T.plannerWeekReasonsV489653(leftover,memory)[0].includes('simplifie le lendemain'));
assert.equal(T.plannerWeekReasonsV489653(leftover,memory)[1],'');
assert.equal(T.plannerWeekReasonsV489653(leftover,memory)[2],'');
assert.equal(JSON.stringify(T.plannerWeekReasonsV489653(plan,memory)),JSON.stringify(reasons),'aucun état de déduplication partagé');
for(const forbidden of ['compatible avec ton repère budget par repas','repose sur une association culinaire déjà validée','s’appuie sur un plat complet déjà référencé'])assert(!raw.includes(forbidden));
assert.equal(raw,fs.readFileSync(path.join(root,'www/scripts/tee-next.js'),'utf8'));
for(const file of ['tee-next.html','www/tee-next.html'])assert(fs.readFileSync(path.join(root,file),'utf8').includes('v4896531-raisons-fil-culinaire-r1'));
(async()=>{
  const result={dataset:{},innerHTML:'',querySelectorAll(){return []}};
  const finance={coverage:100,budgetReferenceCost:37.16,totalDocumented:37.16,strictPackageTotal:27.95,strictPackageItems:5,strictPackagePartial:true,strictPackageCoverage:63,shopRows:[],usePurchaseReference:true};
  await T.plannerRenderInteractiveV4896({result,plan,candidates:[],pTok:new Set(),budget:45,budgetMode:'balanced',servings:1,memoryState:memory,globalBrain:null,tierLabel:'Test',feedbackState:{},userId:'test',generationRound:0,availableDays:7},finance);
  assert.equal(result.dataset.plannerUiVersion,'v4896531');
  assert.equal((result.innerHTML.match(/Pourquoi ce choix/g)||[]).length,1,'le rendu réel doit dédupliquer trois repas successifs');
  
const jsText=require('fs').readFileSync(require('path').join(__dirname,'..','scripts','tee-next.js'),'utf8');
assert(jsText.includes('s’inscrit dans un fil culinaire repris cette semaine'));
assert(!jsText.includes('prolonge un même fil culinaire dans la semaine'));
console.log('OK V489653.1 : motifs factuels, déduplication hebdomadaire, rendu réel, miroirs et cache key.');
})().catch(error=>{console.error(error);process.exitCode=1});
