const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const home=read('scripts/home-smart-cards.js');
const homeW=read('www/scripts/home-smart-cards.js');
const v18=read('scripts/v18-premium.js');
const insp=read('scripts/food-inspiration.js');
const index=read('index.html');
function assert(ok,msg){if(!ok)throw new Error(msg);}
assert(home===homeW,'home-smart-cards mirror mismatch');
assert(home.includes("caption.textContent='Actions du jour'"),'Today caption must be Actions du jour only');
assert(home.includes("if(action==='food-day'){window.mtOpenHomeFoodDayPreview();return;}"),'food-day must open inline preview');
assert(home.includes("if(action==='food-adapter'){window.mtOpenHomeAdapterPreview();return;}"),'adapter must open inline preview');
assert(home.includes("if(action==='composer'){window.mtOpenHomeComposerPreview();return;}"),'composer must open inline preview');
assert(home.includes("if(action==='planner'){window.mtOpenHomePlannerPreview();return;}"),'planner must open inline preview');
assert(home.includes("if(action==='trackers'){window.mtOpenHomeTrackersPreview();return;}"),'trackers must open inline preview');
assert(home.includes('Ouvrir ma journée complète'),'food day full CTA missing');
assert(home.includes('Ouvrir Adapter mon repas en entier'),'adapter full CTA missing');
assert(home.includes('Ouvrir Composer avec TEE en entier'),'composer full CTA missing');
assert(home.includes('Ouvrir le planificateur complet'),'planner full CTA missing');
assert(home.includes('Ouvrir Mes suivis dans le Carnet'),'tracker full CTA missing');
assert(home.includes('Ouvrir mon équilibre complet'),'balance full CTA missing');
assert(home.includes('library.html?focus=trackers'),'tracker direct Carnet focus missing');
assert(v18.includes('id="mtCarnetTrackingShelf"'),'Carnet tracker anchor missing');
assert(v18.includes("focus==='trackers'"),'Carnet tracker focus routing missing');
assert(insp.includes("sessionStorage.getItem('mtComposerSeedV1')"),'composer seed restore missing');
assert(index.includes('v4896556-inline-previews-r1'),'home cache buster missing');
assert(index.includes('v4896556-carnet-focus-r1'),'v18 cache buster missing');
console.log('V4896556 QA OK');
